react-native-async-storage/async-storage

lib/AsyncStorage.js
I've just noticed that the published package is broken on import level. This's going to fix that.
=> Fix published package.

.circleci/config.yml, .eslintrc, README.md, babel.config.js, docs/API.md, docs/Linking.md, example/src/App.js, example/src/examples/ClearSingle.js, example/src/examples/GetSet.js, package.json
Done:
- Added test for `flow` and `lint`
- Added CI config
- Improved docs
- Fixed typo in the example app
=> Create docs for module

react-native-async-storage.podspec
=> Add podfile

ios/RNCAsyncStorage.m
Currently, iOS is failing on imports, so this fixes the issue.
=> Correct imports

.circleci/config.yml
Summary:
---------
Adding missing `attach-to-workspace` step in `publish` job
Test Plan:
----------
N/A
=> [Chore] Attach workspace to publish job

docs/Linking.md
=> Added Android manual linking guide

.github/ISSUE_TEMPLATE/01_bug_report.md, .github/ISSUE_TEMPLATE/02_feature_request.md, .github/ISSUE_TEMPLATE/03_question_discussion.md, .github/PULL_REQUEST_TEMPLATE.md
Summary:
---------
- added missing icons in Issue templates
- fixed grammar in PR template
Test Plan:
----------
=> Docs improvement

.circleci/config.yml
Summary:
---------
Circle did not complain before about it, but it is now. 
Test Plan:
----------
N/A
=> [Chore] Fix publish CI job

lib/AsyncStorage.js
Summary:
---------
It doesn't seem like RNCAsyncStorage is enabled.
Test Plan:
----------
All the current tests should pass.
=> feat: Enable RNCAsyncStorage.

docs/API.md
Summary:
---------
Test Plan:
----------
=> add link to 'getAllKeys'

README.md, docs/Linking.md, lib/AsyncStorage.js
In this release:
- Adds Jest mocks
- Fix Async Storage regression on iOS
- Breaks support for react-native-windows (changing module name) - see:
https://github.com/Microsoft/react-native-windows/issues/2271 
https://github.com/Microsoft/react-native-windows/issues/2270
- Adds docs about manual linking on iOS
Closes: #39, #67, #51, #12,
=> [Release] v1.2.5

.releaserc
Summary:
---------
Fixes release config.
Test Plan:
----------
=> [fix] semantic-release fixes

.releaserc, package.json
Summary:
---------
Rebase with release branch.
=> [chore] Keep up with Release

.circleci/config.yml, .releaserc, CONTRIBUTING.md
Summary:
---------
This brings back semantic releases from master branch. Let's keep it this way, until we can think of a better release/deploy process.
Test Plan:
----------
=> [chore] Setup semantic releases on master

RNCAsyncStorage.podspec
Summary:
---------
Fixes #92 
Test Plan:
----------
Follow repro steps from linked issue
=> Podspecs: correct git tag format

README.md
Summary:
---------
AsyncStorage is still unencrypted, so we need to be clear about this. 
Test Plan:
----------
None
=> docs: add info that storage is still unencrypted

ios/RNCAsyncStorage.xcodeproj/project.pbxproj
Summary:
---------
Fixes: https://github.com/react-native-community/react-native-async-storage/issues/108. I tried to explain the problem in the linked issue. Let me know if you need more information or anything else that I can help?
Test Plan:
----------
- Run a `tvOS` project that uses this library and see the build succeeds
=> Add tvOS to supported platforms

docs/Troubleshooting.md
Summary:
---------
Looks like a simple typo, can be frustrating for those who simply copy paste this code. 
Test Plan:
----------
=> docs: fix typo in troubleshooting

packages/storage-legacy/src/LegacyAsyncStorage.ts
Summary:
---------
LegacyAsyncStorage Implementation using NativeModules AsyncStorage
Test Plan:
----------
=> LegacyAsyncStorage Implementation

.circleci/config.yml, README.md
Summary:
---------
- Update the main readme to cover auto-linking feature.
- Disable failing tests for android (failing silently for `haxm`, going to revisit this later on)
=> Update docs to cover auto-linking 

android/build.gradle, android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
fix  https://github.com/react-native-community/async-storage/issues/159
=> The AsyncTask.THREAD_POOL_EXECUTOR maybe blocked by some other module

docs/advanced/DedicatedExecutor.md, example/android/gradle.properties
Summary:
---------
Docs explaining the usage of a dedicated thread executor for Async Storage.
=> Dedicated executor docs

android/build.gradle, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
Summary:
---------
Keeping up with gradle version for React Native.
Test Plan:
----------
=> Upgrade Gradle version to `3.4.1`

README.md, packages/storage-legacy/README.md, packages/storage-web/.npmignore, packages/storage-web/README.md, packages/storage-web/package.json, packages/storage-web/src/index.ts, packages/storage-web/types/index.d.ts
Prepared small scaffolding for Web backend storage.
=> Prepare for Web storage 

docs/API.md
dot was in wrong place
Summary:
---------
Test Plan:
----------
=> Fix typo in example

README.md
missing word
Summary:
---------
Test Plan:
----------
=> Missing word in README.md

lib/AsyncStorage.js
Summary:
---------
Replace invalid URL
=> Update URL of comments of AsyncStorage.js

example/windows/AsyncStorageExample.sln, example/windows/AsyncStorageExample/Bundle/.gitignore, windows/ReactNativeAsyncStorage/ReactNativeAsyncStorage.vcxproj
Summary:
---------
Switched to `$(ReactNativeWindowsDir)` variable instead of searching for the hard coded path, this unblocks our uses cases inside react-native-windows repo.
Test Plan:
----------
Run the Windows example app as usual.
=> Fix Windows project imports

package.json
Summary:
---------
Include Windows package in NPM package.
=> fix(windows): Include Windows in tarball

.github/workflows/website-deployment.yml, website/README.md
Summary:
---------
Fixing up deployment for website (and forcing one too).
=> chore: GH Action fixup

src/AsyncStorage.native.js
Summary:
---------
Update error message with correct url to jest-integration. Error message leads to 404 page
=> Update error message with correct url to jest-integration

website/docs/Usage.md
correcting the word "exiting" to "existing".
Summary:
---------
Test Plan:
----------
=> correction of word in the Usage.md file

website/docs/Linking.md
Updating the 'MainApplication.java' path
Summary:
---------
Test Plan:
----------
=> docs: Update Linking.md

jest/async-storage-mock.js
Summary:
---------
fixes https://github.com/react-native-community/async-storage/issues/417
Test Plan:
----------
you can use "useAsyncStorage" from jest tests if you are using the mock provided by the library
=> add useAsyncStorage to async-storage-mock.js

README.md
Link was broken. I just updated it to the right subdomain.
=> Updated link to the git pages doc

website/docs/Installation.md
In this PR I have added the installation method for npm.
=> Added installation method for npm

metro.config.windows.js, package.json, yarn.lock
Bumps all build dependencies to latest.
=> chore(deps): bump all dependencies

website/docusaurus.config.js, website/package.json, website/yarn.lock
Bumps all dependencies under `/website`.
Website builds locally. Not sure if there's anything else that should be tested.
=> chore(deps): bump website dependencies

types/index.d.ts
=> Change API URL Documentation

jest/async-storage-mock.js
=> fix: align mock of multiMerge with actual behavior

package.json
We previously published source map files and people are using them.
Resolves #747
n/a
=> fix: also publish source map files

package.json, yarn.lock
Declare support for react-native 0.70
n/a
=> fix: declare support for react-native 0.70

website/docs/Installation.md
Follow Expo's recommendation to use npx
=> Change Expo installation command

package.json
=> fix: declare support for react-native 0.71

website/sidebars.js
=> docs: remove Linking from the side bar

example/ios/Podfile, package.json, react-native.config.js, yarn.lock
Update `react-native.config.js` to accommodate newer `@react-native-community/cli` versions.
n/a
=> chore: update `react-native.config.js` to accommodate newer versions

.circleci/config.yml, .github/workflows/ci.yml
Release `@react-native-async-storage/async-storage` from GitHub
n/a
=> ci: release from GitHub

.github/workflows/ci.yml
Rushed to fix this and made a typo out of habit 🙈
=> fix(deploy): GH Token secret name

.circleci/config.yml, .eslintrc, .github/workflows/ci.yml, package.json, yarn.lock
Getting the ball rolling with tiny dependencies bump and dropping semantic release
closes #929
=> feat(next): Begin work

.github/workflows/ci.yml
Disable credential persistence to ensure our token gets used.
Found the potential solution here: https://github.com/semantic-release/semantic-release/discussions/2557
n/a
=> ci: attempt to fix publishing

.github/workflows/ci.yml
Let's try with Git setup again.
n/a
=> ci: try explicitly setting name/email in Git config

src/AsyncStorage.native.ts, src/RCTAsyncStorage.ts
We don't have a TurboModule implementation yet, but this should be backwards compatible with legacy native module.
n/a
=> refactor: add TurboModule spec

src/AsyncStorage.native.ts
Tell users about how autolinking works.
n/a
=> fix: tell users about how autolinking works

packages/default-storage-backend/package.json, yarn.lock
Widen supported version range.
n/a
=> fix: widen supported version range

.config/tsconfig.base.json, packages/api/package.json, packages/api/src/index.ts, packages/api/tsconfig.json, packages/default-storage/src/helpers.ts, packages/default-storage/src/types.ts, packages/default-storage/tsconfig.json, yarn.lock
`main` currently fails because of TypeScript errors not picked up during PR.
=> chore: fix `tsc` not checking `src/*`

packages/default-storage/windows/ReactNativeAsyncStorage/ReactNativeAsyncStorage.vcxproj
Bump minimum Windows target platform version to 10.0.17763.0.
Resolves #1022
n/a
=> fix(windows): bump minimum Windows target platform version to 10.0.17763.0

packages/default-storage/src/helpers.ts, packages/default-storage/src/types.ts
=> fix: `multiSet` should expect read-only input

packages/website/docusaurus.config.js, packages/website/package.json, yarn.lock
This PR introduces local offline search.
search only works in production
1. generate a new build
2. serve the build
=> docs: Add documentation search

.changeset/config.json, package.json, yarn.lock
Added missing bits from previous PR
=> chore: changeset migration followup 

.github/workflows/website-deployment.yml
=> ci: fix website deployment

.changeset/spicy-hairs-leave.md
Added a change log file to trigger a release.
n/a
=> docs(changeset): Windows: Add New Architecture support
