- .circleci/config.yml
Circle should save fetched modules to a workspace.
> [Fix] CircleCI build

- example/src/examples/GetSet.js
- lib/AsyncStorage.js
It is the same as the [PR](https://github.com/facebook/react-native/pull/22212) that I submitted in react-native repository.
I hope this helps.
> Fixed for supporting flow

- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
Fixes #6 by just invoking the callback without the error.
> Remove error when empty for multi[Remove|Set]

- index.d.ts
- package.json
- types/index.d.ts
> TypeScript support

- example/ios/AsyncStorageExample.xcodeproj/project.pbxproj
- ios/RNCAsyncStorage.m
- lib/AsyncStorage.js
Summary:
---------
Couple of things:
- Example was unlinked, so linked it back
- Uses same directory name as internal Async Storage, so transition is smooth
- Removed reference to RN's internal Async Storage - this sometimes thrown error `.multiMerge` error
- Throws error when not linked
Fixes #40 
Potentially fixes #44 
Test Plan:
----------
Green CI
> [Fix] Use same directory name for storage, couple of fixes

- lib/AsyncStorage.js
Summary:
---------
The [react-native-windows](https://github.com/Microsoft/react-native-windows) repo provides Windows build target support to React Native projects. It provides AsyncStorage support through the module name `AsyncLocalStorage` (exact file is [here](https://github.com/Microsoft/react-native-windows/blob/master/RNWCS/ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs)) but commit 547445c148b18be8bd1476d418e6f3318587b5cb removed the reference to `NativeModules.AsyncLocalStorage` from this repo which broke Windows support. This PR adds that back in.
Test Plan:
----------
Green CI
> fix: Fix Windows support

- types/index.d.ts
Per issue: https://github.com/react-native-community/react-native-async-storage/issues/58
`multiGet` types should allow returning `string | null`, not just string.
Summary:
---------
Test Plan:
----------
> Update types to allow null return from multiget

- .circleci/config.yml
- .releaserc
- CONTRIBUTING.md
Summary:
---------
For now, to avoid scenarios like described in #55, I'm moving away from automatic to "semi-automatic" releases - each version will be cut from `release` branch, which will be done after testing latest changes on `master`.
Test Plan:
----------
Green CI.
> [chore] Changes regarding cutting a release

- lib/AsyncStorage.js
Summary:
---------
React Native's (deprecated) AsyncLocalStorage is being picked up before RNC's.
Test Plan:
----------
All the current tests should still pass.
> fix: Prefer RNC's AsyncStorage over RN's.

- lib/AsyncStorage.js
Summary:
---------
From recent changes, we've moved back to add `LocalAsyncStorage` native module, which consequently fallbacks to deprecated Async Storage on RN Core.
This change reverts this back and add new name, to be used by external storages.
Test Plan:
----------
Green CI.
> Deprecate AsyncStorage from React Native

- README.md
- docs/Linking.md
After the discussions on issue #56 I've noticed that we have missing information about iOS Linking and almost none about the manual linking process, this PR aims to provide this missing info.
No needed, only docs changes.
> docs: Update iOS Linking information

- README.md
- docs/AdvancedUsage.md
- example/e2e/asyncstorage.e2e.js
- example/ios/AsyncStorageExample.xcodeproj/project.pbxproj
- example/ios/AsyncStorageExample/AppDelegate+RNCAsyncStorageDelegate.h
- example/ios/AsyncStorageExample/AppDelegate+RNCAsyncStorageDelegate.m
- example/ios/AsyncStorageExample/AppDelegate.h
- example/ios/AsyncStorageExample/AppDelegate.m
- example/ios/AsyncStorageExample/Info.plist
- example/ios/AsyncStorageExample/RNCTestAsyncStorageDelegate.h
- example/ios/AsyncStorageExample/RNCTestAsyncStorageDelegate.m
- ios/RNCAsyncStorage.h
- ios/RNCAsyncStorage.m
- ios/RNCAsyncStorage.xcodeproj/project.pbxproj
- ios/RNCAsyncStorageDelegate.h
Summary:
---------
Adds a delegate property to `RNCAsyncStorage` to allow custom handling of storage.
Implements #33.
Test Plan:
----------
To manually test the delegate, shake the Simulator (^⌘Z) and toggle
"Set AsyncStorage Delegate". Otherwise, tests for JS have been duplicated for
the native delegate.
> feat: Allow brownfield iOS apps to handle storage.

- package.json
Summary:
---------
`yarn add @react-native-community/async-storage`
when running rn 0.59.0 gives:
warning " > @react-native-community/async-storage@1.2.2" has incorrect peer dependency "react-native@^0.57.0".
Test Plan:
----------
> React Native peer dependency warning

- ios/RNCAsyncStorage.m
Summary:
---------
See: https://github.com/react-native-community/react-native-async-storage/issues/55
Test Plan:
----------
The only type of tests I have already run is:
1. Hardcode set the variable `RCTStorageDirectory` to `RNCAsyncStorage_V1`
2. Run the app & set some values to cache
3. Close the app
4. Reset `RCTStorageDirectory` to `RCTAsyncStorage_V1`
5. Run the app and see that cached values have been migrated
I have performed these tests with and without a pre-existing storage directory and they work in both cases.
My only concerns are the way I am currently handling errors. If something goes wrong an `NSException` is thrown which will trigger a SIGABRT shutdown of the app since it is never caught. I am not extremely experienced with error handling in Objective-C so perhaps …
> iOS clean migration from RNCAsyncStorage_V1 to RTCAsyncStorage_V1

- RNCAsyncStorage.podspec
- docs/Linking.md
Summary:
---------
Multiple people have reported that RNCAsyncStorage fails to build after #35. See https://github.com/react-native-community/react-native-async-storage/pull/35#issuecomment-482604705, #73, and #74.
After a little discussion, we agreed to rename the `.podspec` and the name of the Pod to be more in line with Apple's naming guidelines and the rest of the community. Unfortunately, this means that the next upgrade will break.
I got a little impatient knowing that I broke the latest release so I went ahead and implemented the fix. Sorry if you've already started looking at this.
Test Plan:
----------
I used https://github.com/timmywil/react-native-async-storage-1.3.1, kindly provided by @timmywil, for testing.
Migration Plan:
---------------
Even though `react-native link` will …
> fix: Fixed failing to find headers when linked with Pods.

- ios/RNCAsyncStorage.xcodeproj/project.pbxproj
Summary:
---------
iOS headers are being included in the final archive, making Xcode generate generic archives instead of IPAs. Moving the headers to project only should address this issue. See #76.
Test Plan:
----------
In an app that manually links to AsyncStorage, archiving should generate an IPA and not a generic archive.
> fix: Exclude headers from iOS archive.

- example/android/app/build.gradle
- example/android/app/src/androidTest/java/com/asyncstorageexample/DetoxTest.java
- example/android/build.gradle
- example/android/settings.gradle
- package.json
- yarn.lock
Upgrade detox:
---------
Upgrade detox for xcode 10 and above support
closes #94
> chore: upgrade detox

- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
When building DexMerger throws an error due to duplicate imports of the package
Summary:
---------
Test Plan:
----------
build a release version
> fix compilation error

- docs/Troubleshooting.md
Summary:
---------
Added a page with things to try out for some build related issues.
Test Plan:
----------
n/a
> chore: add things to try for common issues

- ios/RNCAsyncStorage.h
Summary:
---------
Was receiving a compile error when running `react-native run-ios`
```
node_modules/@react-native-community/async-storage/ios/RNCAsyncStorage.h:10:9:
'RNCAsyncStorage/RNCAsyncStorageDelegate.h' file not found
#import <RNCAsyncStorage/RNCAsyncStorageDelegate.h>
~~ ~~~~~^~~
```
A similar fix was required in other libraries, since the file is in the same directory as the header. You can require it without a namespace.
Test Plan:
----------
Run `react-native run-ios` and if it compiles then it was a success.
> Fixes 'RNCAsyncStorage/RNCAsyncStorageDelegate.h' file not found

- jest/async-storage-mock.js
To unify the types for all callbacks, also allow `undefined` for the callback of `getItem`.
Summary:
---------
Flow complains because the `getItem` mock doesn't have an optional callback. Unify the callback types to include a `void` for the specific mock as well to mitigate.
Test Plan:
----------
To test, make sure that the `getItem` also allows a callback that is `undefined` without it throwing a Flow error.
> fix: Allow void for ItemGetCallbackType in mock storage

- .circleci/config.yml
- .prettierrc
- babel.config.js
- core/__tests__/AsyncStorage.test.ts
- core/__tests__/core.test.ts
- core/src/AsyncStorage.ts
- core/src/defaults.ts
- core/src/index.ts
- core/types/index.d.ts
- jest.config.js
- package.json
- tsconfig.json
- yarn.lock
> [v2] Initial Core implementation

- docs/Jest-integration.md
Fix a small documentation issue with the `transformIgnorePatterns` suggested fix for performing proper transformations on the mocks for Jest compatibility. Need to add a trailing `/` to the regex for the transform ignore, otherwise it will match all packages in `node-modules` that start with the string `react-native`!
> Add trailing `/` to `transformIgnorePatterns`

- .npmignore
Summary:
---------
Add `ios/build` directory to the `.npmignore` file.
Android build directory is already part of the `.npmignore`, but it was not done for iOS build directory, resulting in the published package to contain the whole local iOS build directory :(
Test Plan:
----------
No code change, and no use of any files from the build directory in the code base, so not real testing done apart from running `npm pack` to make sure that the iOS build directory was properly kept outside the npm package.
> Add ios build directory to .npmignore

- lib/AsyncStorage.js
Summary:
---------
Came across a broken link in my terminal output.
The previous link was 404ing since the docs were moved to a different dir.
Test Plan:
----------
Attempt to navigate to https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Jest-integration.md in your browser. This should 404.
Attempt to navigate to https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md. This should work fine.
> fix: broken link in AsyncStorage.js

- jest/async-storage-mock.js
Summary:
---------
The `AsyncStorage.getAllKeys()` method in the Jest mock wasn't mocked to return the mock storage keys. This changes the mock such that `getAllKeys` will by default return the mock storage keys. Without this change, lib users will have to mock `getAllKeys`.
Test Plan:
----------
I don't have a perfect test plan, but you can test by writing a Jest test that will have code that executes `AsyncStorage.getAllKeys()`. The default mock will not return the mock storage keys.
> fix: getAllKeys() Jest mock returns array of keys

- RNCAsyncStorage.podspec
Summary:
---------
After upgrading my tvOS project to RN 0.60+, I found the new pod auto-linking feature wasn't working for async-storage on tvOS due to support not being specified for tvOS. Adding this to the podspec allows `pod install` to work correctly for tvOS.
Test Plan:
----------
Try and use async-storage in a tvOS project on RN 0.60+. Note that `pod install` will throw an error (tvOS not supported). Update the podspec as per this PR and try again and it will work.
> Add tvOS to podspec supported platforms

- .gitignore
- android/build.gradle
- android/gradle.properties
A slightly different approach to #207 
This wraps the Android Gradle plugin dependency in the `buildscripts` section of `android/build.gradle` in a conditional:
```
if (project == rootProject) {
// ... (dependency here)
}
```
The Android Gradle plugin is _only_ required when opening the project _stand-alone_, not when it is _included as a dependency_. By doing this, the project opens correctly in Android Studio, and it can also be consumed as a native module dependency from an application project **without** affecting the app project (avoiding unnecessary downloads/conflicts/etc).
Android Studio and/or Gradle installed locally.
Open `android` in Android Studio:
```sh
studio android/
```
Or:
Generate a Gradle wrapper on the fly, and build on command line:
```sh
cd android/
gradle wrapper …
```
> Update build.gradle setup

- packages/core/__tests__/AsyncStorage.test.ts
- packages/core/__tests__/core.test.ts
- packages/core/docs/Writing_Storage_Backend.md
- packages/core/src/AsyncStorage.ts
- packages/core/src/extension.ts
- packages/core/types/index.d.ts
- packages/storage-legacy/src/index.ts
Summary:
---------
Storage extension is a small proxy that allows accessing Storage instance's methods in a safe way. This allows extending the standard AsyncStorage API with additional functionality.
To Do:
---------
Test Plan:
----------
Green CI.
> [v2] Storage extension

- lib/AsyncStorage.js
Summary:
---------
Added warning on iOS when the value in the second argument of the `setItem` method is not a string.
Test Plan:
----------
Change the second argument of the `setItem` method in `example/src/examples/GetSetClear.js`, line 41 to non-string type and then try to increase the stored value. The warning will appear.
Example:
```
await AsyncStorage.setItem(STORAGE_KEY, newNumber);
await AsyncStorage.setItem(STORAGE_KEY, {newNumber});
await AsyncStorage.setItem(STORAGE_KEY, [newNumber]);
await AsyncStorage.setItem(STORAGE_KEY, null);
```
> feat: add warning to set functions when value is not a string (#230)

- lib/AsyncStorage.js
We currently try to load builtin native modules before trying to
fallback to platform provided native modules. Reversing this order
allows the platform to provide the AsyncStorage implementtion even if
on a platform that async-storage already supports. This ability can
be useful in hosted scenarios where we may want more control over how
data for an individual React Native instance is stored.
This should be entirely unneeded for AsyncStorageV2 since we have IStorageBackend.
> Prefer PlatformLocalStorage Over Other Native Modules

- packages/storage-legacy/ios/RNCAsyncStorage.m
Summary:
---------
Removed migration of `RNCAsyncLocalStorage_V1` to `RCTAsyncLocalStorage_V1` in preparation for AsyncStorage v2.
Test Plan:
----------
All current tests should pass.
> fix(iOS): Remove RNC -> RCT storage migration

- lib/AsyncStorage.js
Summary:
---------
Android did not show errors when `null`/`undefined` values were passed. This PR fixes that.
Closes #253 
Test Plan:
----------
1. Try setting a  `null`/`undefined` value to AsyncStorage.
2. Note that errors where thrown.
> fix(android): throw error when value is `null`

- ios/RNCAsyncStorage.m
Summary:
---------
This is to distinguish "manifest file does not exist or is corrupted" and "have no access to the manifest file yet" cases.
Starting with an empty dictionary is a reasonable fallback in case the manifest does not exist or cannot be parsed because of being corrupted or incompatible. However doing so might lead to unnecessary data loss when the app simply has no access to its documents yet due to iOS data protection (if enabled and when the app launches while the device is locked due to e.g. geofencing, silent notification, external accessory, etc).
Test Plan:
----------
Enable data protection in your RN iOS app, then trigger a geofencing event or a silent push notification to launch the app while the phone is locked and files are not readable. If the app tries to access …
> Don't reset the storage when the manifest file cannot be read because of iOS data protection

- docs/API.md
Summary:
---------
Just added a missing colon in the documentation
Test Plan:
----------
Check if docs/API.md:115 have a colon in the end of the line, after the `'black'` string.
> Adds missing colon in the documentation

- ios/RNCAsyncStorage.m
- package.json
Summary:
---------
Right now on iOS, the data is stored in the Documents directory (NSDocumentDirectory) on iOS and the caches directory (NSCachesDirectory) on tvOS.
These are not the best locations for the following reasons:
* NSDocumentDirectory- this folder is visible on iOS in scenarios where you can view the Files structure. For instance, in Word/PPT/Excel, a user can tap through to this and see a folder titled "RCTAsyncLocalStorage_V1".
* NSCachesDirectory- Apple documents this as a location that can get purged in low memory scenarios "the system may delete the Caches directory on rare occasions when the system is very low on disk space."
This fix moves the location to the Application Support directory (NSApplicationSupportDirectory). This directory is documented by Apple as …
> [FIX] Move the storage location on iOS to Application Support

- lib/AsyncStorage.js
Summary:
---------
Facebook changed the URL of the React Native docs from `facebook.github.io/react-native` to `reactnative.dev`.  This PR updated all the links pointing to the old docs site with the updated link. 
Test Plan:
----------
No code changed. Only comments were updated.
> update react native doc links with new docs url

- ios/RNCAsyncStorage.m
Summary:
---------
fixes issue described in https://github.com/react-native-community/async-storage/issues/301
Test Plan:
----------
you can use my sample repo here: https://github.com/frankenthumbs/AsyncStorageUpgradePOC and use the repro steps but the gist is, on iOS:
1. save something in async storage on version 1.2.1
2. upgrade to latest
3. noticed data doesn't get wiped
> Create [bundle ID] folder during migration if none exists

- lib/AsyncStorage.js
Just a one-line error message change because there is no `--clearCache` flag on packager.
> update Error message

- .gitignore
- app.json
- example/index.js
- lib/AsyncStorage.web.js
- package.json
- yarn.lock
Summary:
---------
- fix: https://github.com/react-native-community/async-storage/issues/52
- Migrate `react-native-web` AsyncStorage to this package
Test Plan:
----------
- Added web support to legacy test `yarn start:web`
- You'll need to link `@react-native-community/async-storage` to emulate metro resolution.
> [LEGACY] Add web support to AsyncStorage

- README.md
- docs/API.md
Summary:
---------
Clarified documentation regarding basic use cases like installation, storing object data, unencrypted nature, etc.
Test Plan:
----------
Documentation changes only.
> Documentation clarification

- README.md
We've been recommending devs use `npx pod-install` since it will attempt to install CocoaPods CLI if it's not available on the computer (cite [React Navigation setup guide](https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-a-bare-react-native-project)). This has proved very useful for Expo users who are now migrating to the bare workflow and want to use community packages in their projects.
> Recommend npx pod-install for setup instructions

- docs/Linking.md
Summary:
---------
Typo fixed.
Test Plan:
----------
Not required.
> docs: Fix typo

- RNCAsyncStorage.podspec
Refs #296
This small PR updates the `podspec` file and adds `osx` platform there which fixed Pods installation on macOS:
I have tested the change on the local working copy of `async-storage`.
> fix Pods installation on macOS

- .github/CODEOWNERS
- package.json
- src/AsyncStorage.native.js
- src/RCTAsyncStorage.expo.js
- src/RCTAsyncStorage.js
Summary:
---------
Currently tools like AWS Amplify and redux-persist need separate instructions for using AsyncStorage whether you are in an Expo managed project or a bare React Native project, because Expo manage projects do not yet include @react-native-community/async-storage. We would like to include it, but it's a bit trickier than most packages due to complexity around scoping storage access when switching between different projects within the Expo client app.
In order to let library authors just tell people to use @react-native-community/async-storage, I think the easiest solution for now is to swap out the backing native module when in the Expo managed workflow to the solution provided by React Native, which is still included in core as recently as 0.62.2. I did this by moving …
> Swap the native module used when in Expo managed workflow

- package.json
Summary:
---------
This small PR fixes `test:lint` command on Windows by removing single single quotes (they can be also replaced with the escaped double quotes, but removal is a simpler solution).
> ...you have to quote your parameter (using double quotes if you need it to run in Windows)...
More information [here](https://eslint.org/docs/user-guide/command-line-interface).
Test Plan:
----------
`test:lint` run has been successful after the change.  Tested on the macOS and Windows.
> fix test:lint command on Windows

- website/docs/advanced/Jest-integration.md
Summary:
---------
At the moment in Jest Integration if you try to access the link to AsyncStorageMock implementation you will get a 404 since the link currently is : `https://github.com/react-native-community/async-storage/blob/master/website/docs/jest/async-storage-mock.js`.
The new right link should be : https://github.com/react-native-community/async-storage/blob/master/jest/async-storage-mock.js.
This link change should fix the issue.
Test Plan:
----------
Test plan should be checking if the link now redirects to the right page.
> Fix link to Mock Implementation [DOCS]

- .github/workflows/website-deployment.yml
- website/README.md
Summary:
---------
Instead of using flacky SSH, this PR changes GH deployment to use HTTPS instead.
> chore: change settings for GH pages deployment

- website/docs/Usage.md
Summary:
---------
Add `const` for consistent with storeData example
> Add const for consistent with storeData example

- website/docs/API.md
Summary:
---------
Fix API typos
Test Plan:
----------
No test required
> Fix API typos

- website/docs/advanced/Jest-integration.md
In the sentence 'Follow those steps to add a mocked `Async Storage` module', these should be used in place of those.
> Fix typographical error

- src/RCTAsyncStorage.expo.js
Summary:
---------
At Expo we're on the verge of enabling TurboModules in SDK 39 (https://github.com/expo/expo/pull/9687). While we haven't added the native code for this module to the SDK yet, we want to maintain the `.expo.js` fallback, so it resolves with the React Native's `AsyncStorage`.
Test Plan:
----------
I have verified manually that copying and pasting this code to an appropriate file in `node_modules` for a running Expo project fixes the `[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.` error.
The `if (TurboModuleRegistry)` helps to not break this code on older versions of RN which do not have TMR (I hope).
> Add support for enabled TurboModules in Expo

- website/docs/Installation.md
- website/docs/Usage.md
Summary:
---------
Closes #398
Relative links now work even if there's a `/` at the end of URL.
This issue was related to https://github.com/facebook/docusaurus/issues/2298
Test Plan:
----------
Go to https://react-native-community.github.io/async-storage/docs/usage/ and click on "head over to API section"
> docs: fixed relative links

- src/hooks.js
- src/index.js
Summary:
---------
Including `react-native-community/async-storage` in a new project with flow doesn't actually work due to the index file not having the flow annotation. (Blank project with `[declarations] node_modules/**` in the flowconfig, flow version 0.132.0)
This change adds flow annotations. Runtime wise this is only a comment and thus can't break anything other than flow itself (which still works).
Test Plan:
----------
`yarn test` still works.
I'm not completely familiar with how the build process works, but my understanding is that the .flow files in lib will be copied over as is. Thus, the output would look like this, and flow typing would now work:
If this looks good, I can also bump the version before merging if you'd like.
> Add flow annotation to index & hooks

- windows/ReactNativeAsyncStorage/DBStorage.cpp
- windows/ReactNativeAsyncStorage/RNCAsyncStorage.h
Summary:
---------
On Windows `getAllKeys` was reporting the correct results, but also an empty array error. Unlike the multi* methods, these expect a single error, not an array of errors.
The fix is to change the type sent by the windows implementation from an array to a single object. That object is also just a null value, since there are no errors being reported currently by the windows implementation.
Test Plan:
----------
Manually validated with the repo's example app on Windows. Also tested by patching to a react-native-windows app that was already using async storage and failing on `getAllKeys`.
The test app doesn't contain any usage of `getAllKeys`, which is probably why this was missed.
> fix: Errors reported from getAllKeys/clear [WINDOWS]

- RNCAsyncStorage.podspec
Summary:
---------
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Test Plan:
----------
Use this branch to install with an app running on Xcode 12.
> fix: Xcode 12 compatibility

- ios/RNCAsyncStorage.m
Summary:
---------
Bringing back tvOS support that was lost some time ago. Fixes https://github.com/react-native-community/async-storage/issues/416
Test Plan:
----------
Green CI.
Test AsyncStorage on tvOS
> fix: tvOS support

- example/ios/AsyncStorageExample/Info.plist
- ios/RNCAsyncStorage.m
- website/docs/advanced/Backup.md
- website/docs/advanced/BrownfieldIntegration.md
- website/docs/advanced/DedicatedExecutor.md
- website/docs/advanced/IncreaseDbSize.md
- website/sidebars.js
- website/src/components/Platform.js
Summary:
---------
Addressing https://github.com/react-native-community/async-storage/issues/342
I could not reproduce this myself. Saving data, forcing iCloud backup, removing and installing again does not retain the data. This is mostly for anyone who can successfully reproduce the issue mentioned in #342.
Test Plan:
----------
> feat(iOS): Toggle backup feature 

- website/docs/API.md
- website/docs/Installation.md
- website/docs/Linking.md
- website/docs/Usage.md
- website/docs/advanced/Jest-integration.md
- website/docs/help/Troubleshooting.md
Summary:
---------
Updating documentation to point to new npm organization
> docs: Update docs to reflect organization change

- .circleci/Brewfile.android
- .circleci/Brewfile.ios
- .circleci/config.yml
- package.json
- yarn.lock
Summary:
---------
`yarn install` fails because Detox fails to build with Xcode 12.
Resolves #454.
Test Plan:
----------
1. Make sure the repo is clean: `git clean -dfqx`
2. Run `yarn`
> ci(iOS): Fix yarn install failing with Xcode 12

- .flowconfig
- .github/ISSUE_TEMPLATE/01_bug_report.md
- README.md
- example/__tests__/App.js
- example/examples/GetSetClear.js
- example/examples/MergeItem.js
- example/jest.setup.js
- package.json
- src/AsyncStorage.native.js
- src/RCTAsyncStorage.expo.js
- types/index.d.ts
- website/docs/advanced/DedicatedExecutor.md
- website/docs/advanced/Jest-integration.md
- website/docusaurus.config.js
Summary:
---------
We still have references to `@react-native-community` that we need to update.
Test Plan:
----------
> fix: update old references to @react-native-community

- RNCAsyncStorage.podspec
Summary:
---------
AsyncStorage fails to build with RN 0.63:
```
[!] Unable to find a specification for `React-Core` depended upon by `RNCAsyncStorage`
```
Resolves #457.
Test Plan:
----------
CI build should pass.
> fix(iOS): Unable to find a specification for `React-Core`

- .circleci/config.yml
- .releaserc
- package.json
- yarn.lock
Summary:
---------
Setting up semantic releases. Every merge to master, after successful tests, means a new release.
> chore: Semantic release setup

- android/build.gradle
Summary:
---------
AsyncStorage assumes that it is installed in `node_modules` in the parent folder. This may not always be the case.
Test Plan:
----------
Android CI should pass.
> fix(Android): Find react-native using node module resolution

- .github/ISSUE_TEMPLATE/01_bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
Ask bug reporters to provide output of `react-native info` so we can better understand their environment.
This doesn't affect any code.
> chore: Ask bug reporters to provide output of `react-native info`

- .gitignore
- .npmignore
- .vscode/extensions.json
- CONTRIBUTING.md
- example/App.js
- example/ios/AsyncStorageExample/AsyncStorageDevSupport.m
- example/macos/AsyncStorageExample-macOSUITests/AsyncStorageExample_macOSUITests.m
- example/windows/AsyncStorageExample/App.cpp
- example/windows/AsyncStorageExample/App.h
- example/windows/AsyncStorageExample/ReactPackageProvider.cpp
- example/windows/AsyncStorageExample/ReactPackageProvider.h
- example/windows/AsyncStorageExample/pch.h
- ios/RNCAsyncStorage.h
- ios/RNCAsyncStorage.m
- ios/RNCAsyncStorageDelegate.h
- metro.config.windows.js
- package.json
- windows/ReactNativeAsyncStorage/DBStorage.cpp
- windows/ReactNativeAsyncStorage/DBStorage.h
- windows/ReactNativeAsyncStorage/RNCAsyncStorage.h
- windows/ReactNativeAsyncStorage/ReactPackageProvider.cpp
- windows/ReactNativeAsyncStorage/ReactPackageProvider.h
- windows/ReactNativeAsyncStorage/pch.h
Ran `clang-format` on everything.
This shouldn't affect anything but CI should all pass.
> chore: Run clang-format on everything

- example/examples/MergeItem.js
- package.json
- webpack.config.js
- yarn.lock
The example app is currently broken due to `@react-native-async-storage/async-storage` not being resolved correctly.
Resolves #472.
1. Run `yarn`.
2. Run `yarn start:web`.
3. Once the dev server is running, press `w` to open the project in browser.
4. The example should work as expected.
> chore(web): Fix start:web

- .github/workflows/ci.yml
- example/app.json
- example/macos/AsyncStorageExample-macOSUITests/AsyncStorageExample_macOSUITests.m
- package.json
- scripts/macos_e2e.sh
It looks like the macOS CI was accidentally deleted in #369. This change restores it.
macOS CI should pass.
> ci(macOS): Restore CI pipeline

- website/docs/API.md
Missed property `hobby` on console.log after merging items
> Fix mergeItem API documentation

- .circleci/config.yml
CircleCi has been failing on brew dependencies restoration on iOS, probably due to executor version bump. This PR clears cache and only stores brew cache files.
> chore(ci): save only brew cache files

- RNCAsyncStorage.podspec
Fix for issue described in https://github.com/react-native-async-storage/async-storage/issues/509
Build a new RN project referencing PR branch
```
npx react-native init RNAsyncStorage && cd RNAsyncStorage
yarn add https://github.com/stu-dev/async-storage#fix/xcode-12-use-frameworks
```
- Add `use_frameworks!` to Podfile (also disable flipper)
```
npx pod-install
yarn ios
```
> Fix ios build for xcode 12 + use_frameworks!

- package.json
Our React version requirement needs to match what react-native depends
on. Changing it to specific versions rather than a blanket 16.x or 17.x
to make sure that we stay compatible.
Resolves #535.
No tests needed. CI should pass.
> fix: add react 17 to peer dependencies

- .github/ISSUE_TEMPLATE/01_bug_report.md
Since we're getting a lot of reports from Expo users, we should also include it in our bug report template.
There is nothing to test.
> chore: add Expo to bug report template

- website/docs/Installation.md
Broke out the 2 different ways to install (NPM or Yarn) to be one-liners, so that the "copy code" functionality is helpful.
Currently when clicking the copy code from the code block, it copies both NPM and Yarn. This change just breaks them out for a quick one line copy depending on the developer's need.
| Before      | After |
| ----------- | ----------- |
| <img width="837" alt="Screen Shot 2021-02-16 at 3 22 52 PM" src="https://user-images.githubusercontent.com/1774589/108117719-48cae480-706b-11eb-99b4-cb8b4f078be3.png"> | <img width="839" alt="Screen Shot 2021-02-16 at 3 23 00 PM" src="https://user-images.githubusercontent.com/1774589/108117728-4ec0c580-706b-11eb-9a31-22c5832cb2db.png"> |
Screenshots above shows the before and after.
> [docs] Update to Installation Page

- .circleci/config.yml
- src/shouldFallbackToLegacyNativeModule.js
Fixing the export for Expo fallback method, preventing from using Async Storage.
Also, releases should be done after all e2e passed.
Green CI.
> fix: Expo fallback function exporting

- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageExpoMigration.java
- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageMigration.java
- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
Expo users who publish an app with `expo build:android` will use a database file like `RKStorage-scoped-experience- <encoded-project-slug>` when they eject, the 
database file will be `RKStorage`, this effectively prevents many users from being able to eject https://github.com/expo/expo/issues/8220 and use this package.
This PR introduces parity for an [iOS feature](https://github.com/react-native-async-storage/async-storage/blob/af0677c43e5087404b0def0dd084a69e1930cbf5/ios/RNCAsyncStorage.m#L395-L399) that migrates the database directory.
1. Check to see if `RKStorage` file exists (if not bail out).
2. Query all files in the database directory starting with `RKStorage-scoped-experience-`
3. Get the most recently modified file to migrate. This is useful because users who change their slug …
> Created Android scoped storage migration method

- ios/RNCAsyncStorage.m
This solves [an issue](https://github.com/expo/expo/issues/8220) users encountered with the following process:
- build app with managed workflow, submit to store, users use it, data saved to RCTAsyncLocalStorage.
- eject app, build and resubmit, users update app and now @react-native-async-storage/async-storage native module is linked and it looks for data in RCTAsyncLocalStorage_V1, no data found - resulting in data loss.
Something that I noticed while implementing this was that it is theoretically possible (although extremely unlikely) that a user would have both an old storage directory and an Expo storage directory ("RNCAsyncLocalStorage_V1" and "RCTAsyncLocalStorage"). To handle this case, I added `RCTGetStoragePathForMigration`.
The Android side of this migration is handled in #559 …
> Migrate Expo storage directory on iOS

- src/AsyncStorage.native.js
- For cases when two or more key values pairs are passed unintentionally as arguements to multiSet.
resolves #519
As I ran and went through the e2e tests, observed that there are no tests aded for `multiSet` and `multiGet`. As this is an exception that is being added to `multiSet`, would not be ideal to create the tests for the same.
> feat: add exception when array is passed for 2nd arg

- .circleci/config.yml
- android/build.gradle
- android/gradle.properties
- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java
- android/src/main/java/com/reactnativecommunity/asyncstorage/SerialExecutor.java
- android/src/main/java/com/reactnativecommunity/asyncstorage/next/ArgumentHelpers.kt
- android/src/main/java/com/reactnativecommunity/asyncstorage/next/ErrorHelpers.kt
- android/src/main/java/com/reactnativecommunity/asyncstorage/next/StorageModule.kt
- android/src/main/java/com/reactnativecommunity/asyncstorage/next/StorageSupplier.kt
- android/src/test/java/com/reactnativecommunity/asyncstorage/next/ArgumentHelpersTest.kt
- android/src/test/java/com/reactnativecommunity/asyncstorage/next/StorageTest.kt
- android/src/test/java/com/reactnativecommunity/asyncstorage/next/TestUtils.kt
- android/testresults.gradle
- example/App.js
- example/android/build.gradle
- example/android/gradle.properties
- example/examples/Basic.js
- example/examples/GetSetClear.js
- package.json
- scripts/android_e2e.sh
- website/docs/Linking.md
- website/docs/advanced/BrownfieldIntegration.md
- website/docs/advanced/DedicatedExecutor.md
- website/docs/advanced/IncreaseDbSize.md
- website/docs/advanced/Next.md
- website/sidebars.js
Current implementation of Sqlite access is cumbersome, error prone and produces [some](https://github.com/react-native-async-storage/async-storage/issues/498) hard to reproduce [errors](https://github.com/react-native-async-storage/async-storage/issues/355) to users. This PR aims to improve our native implementation of SQLite access and thread control. 
This PR introduced the "next" storage implementation. [Room](https://developer.android.com/training/data-storage/room) has been used for database access, and [Coroutines](https://kotlinlang.org/docs/coroutines-overview.html) to handle asynchronous work.
I tried to reuse old database file, but due to it having a SQLite bug (where `primary key` can be null, which is a SQLite violation that Room is guarded against) I had to provide a …
> feat(android): Use Room library for persistent storage

- package.json
Install fails on android using next version because of [this line in build.gradle](https://github.com/react-native-async-storage/async-storage/blame/75c571b7b1265e7d5599e0b9e38e19acb6004181/android/build.gradle#L72) created by @Krizzu. It requires a file that is not included in the bundled async storage library.
```
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* Where:
Build file '~/project/node_modules/@react-native-async-storage/async-storage/android/build.gradle' line: 72
* What went wrong:
A problem occurred evaluating project ':react-native-async-storage_async-storage'.
> Could not read script '~/project/node_modules/@react-native-async-storage/async-storage/android/testresults.gradle' as it does not exist.
* Try:
Run with --stacktrace …
```
> Added testresults.gradle in bundle as it is required to install on android using next storage

- package.json
AsyncStorage doesn't depend on `react` but declares it in `package.json`.
Resolves #578.
> fix: AsyncStorage doesn't depend on `react`

- website/docs/advanced/BrownfieldIntegration.md
Java example for Android Brownfield integration is not up-to-date based on the current implementation of the next-storage (Androidx Room usage).
> Update Java example for Brownfield integration

- ios/RNCAsyncStorage.h
In using a custom `RNCAsyncStorageDelegate` subclass to customized the storage of our data into a shared group container, we have needs to expose this method that is currently private (and exposed to ReactNative via a RCT_Export macro) to the header file.
Since we have past versions of our app that was not stored in the custom storage location, but rather the default location, we run some native migration logic when we first load RNAsyncStorage from RCTBridge to see if we need to migrate. We read out each value by key from the default storage and write those keys using our delegate backed instance and then removing from the default storage location.
It would be nice to simply expose this on the native side.
I've included the example export and import logic (in swift) we are using  for …
> Expose the getAllKeys so that natively we can access all the keys

- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncLocalStorageUtil.java
- android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java
- android/src/main/java/com/reactnativecommunity/asyncstorage/next/StorageSupplier.kt
From Pie and up, Android started to use Write-ahead logging (WAL) by default, instead of journal rollback. WAL does not write directly to the database file, rather to the supporting WAL file. The content of WAL file is "flushed" to original DB file (this action is called a **checkpoint**), when page size threshold is reached (default is 1000).
Because of that, migration to Next storage might not be successful, because RKStorage database content might still be in WAL file (and Next AsyncStorage uses RKStorage file to rehydrate itself). This PR introduces a helper that will make sure we force **checkpoint**, to always have the latest content on db file, before migrating.
@EvanBacon I suspect we'd want the same thing happen for Expo migration as well?
> fix(next storage): Force SQLite checkpoint on Pie and up

- .github/workflows/stale.yml
Adds a workflow for cleaning up old issues. By the default, issues/prs are marked as stale after 60 days of inactivity, and closed 7 days after being marked. Issues are exempt if they are labeled `help wanted :octocat:` or `WIP`.
There's currently no way to test this. It will have to be run over-night.
> chore: add 'Close Stale Issues' workflow to clean up old issues

- jest/async-storage-mock.js
- package.json
- src/AsyncStorage.js
- yarn.lock
Replaces deprecated [deep-assign](https://www.npmjs.com/package/deep-assign) with [merge-options](https://github.com/schnittstabil/merge-options).
Resolves #374.
Supersedes #601.
> fix(web): replace deprecated deep-assign with merge-options

- package.json
Declares support for react-native 0.65 and for react-native-macos/-windows canaries.
Also removes `resolutions` since metro dependencies should be in sync now.
Resolves #658.
There's nothing to test.
> fix: declare support for react-native 0.65

- jest/async-storage-mock.js
Users are hitting `SyntaxError: Cannot use import statement outside a module` using `/jest/async-storage-mock.js` in latest version.
Resolves #660
Tests should pass.
> fix(mock): cannot use import statement outside a module

- website/docs/debugging/communityPackages.md
- website/sidebars.js
add community packages inside the debugging section listing the packages helpful for debugging for
Flipper and Non-Flipper projects
re #669
> docs(website): add debugging section with community packages

- website/docs/Installation.md
Since React Native for macOS 0.63, autolink works out-of-the-box as long as `platform :macos, '10.14'` is set in Podfile)
See #587
> docs(website): update auto-linking info for macOS

- .github/workflows/ci.yml
- example/.gitignore
- example/windows/ReactTestApp.sln
- package.json
- yarn.lock
- Bumps actions/setup-node to v2.4.1
- Bumps microsoft/setup-msbuild to 1.0.3
- Bumps react-native-test-app to 0.9.0
- Bumps react-native-windows to 0.63.41
Windows CI should pass.
> chore(windows): fix windows build

- .circleci/config.yml
- android/build.gradle
- example/android/build.gradle
- package.json
- src/AsyncStorage.native.js
- website/docs/Limits.md
- website/docs/advanced/Next.md
- website/sidebars.js
- yarn.lock
Sorry for pushing it into one PR. Got a couple of fixes/improvements coming:
This also changes the way it handles the error from original design - previously, if we'd call many `multiGet` for different keys, they'll be batched into one native call. If any of them failed, the rest of them fail too, but, only the failed one will get the error message, while the rest will be resolved as `undefined` values, creating false negatives. This is now changed, so that once one multiGet fails, every other batched call will throw the same error.
I tried to get everything to the latest version. Turns out, Room, with version 2.4.0 (where Apple M1 support is fixed) needs also increased `compileSdk` version bumped to 31 (latest one). It'd be bad for a library to dictate this version, so instead hardcoding …
> fix: Multiple improvements + docs update

- android/build.gradle
Could reproduce this in a clean project, but not on our example app. Because method used inside `buildscript` is not reachable, I instead read properties directly.
> fix: Gradle build failing for version 1.15.10

- android/build.gradle
- example/android/build.gradle
@tido64 said:
> Unfortunately, we cannot remove JCenter without breaking people on older versions of React Native:
I disagree with it and I will proof soon:)
Refs: #610, #680, #681, #666, #611
I was read some treads in this repo and saw the [wrong conclusion](https://github.com/react-native-async-storage/async-storage/issues/610#issuecomment-917394117):c
I guess @tido64 gets error because in this repo use [react-native-test-app](https://github.com/microsoft/react-native-test-app) for example 
react-native-test-app dont have jcenter() into [build.gradle](https://github.com/microsoft/react-native-test-app/blob/trunk/android/build.gradle)
But old react-native project have  jcenter() inside [build.gradle](https://github.com/Bibazavr/AsyncStorageOldRN/blob/main/android/build.gradle) and all …
> chore(jcenter): remove usage of jcenter()

- .circleci/config.yml
- .releaserc
- package.json
- yarn.lock
- Updated semantic-release package version
- Added settings to generate CHANGELOG file + auto bump package.json (not happening now)
> chore: Improve releases

- .circleci/config.yml
- .releaserc
- package.json
- types/index.d.ts
- yarn.lock
According to [with-jest-setup-file jest integration](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest#with-jest-setup-file), I tried to test `app.test.tsx` file using [ts-jest](https://kulshekhar.github.io/ts-jest/) and followed 
```ts
import mockAsyncStorage from '@react-native-async-storage/async-storage/jest/async-storage-mock';
```
throws ts(7016) error.
If you use this change with ts-jest, the error disappears.
> chore: add type definition for jest mock

- src/AsyncStorage.native.js
Whenever you pass `null` as a value for `.setItem()`, you will see an error. It will tell you to use `.remove` instead, however that method doesn't exist, it should be `.removeItem`. I think so, at least 🤷 
You can test this by throwing the error, see the example below.
```js
import AsyncStorage from '@react-native-async-storage/async-storage';
AsyncStorage.setItem('bla', null);
```
> Fix wrong method referenced in validated input warning

- example/windows/ReactTestApp.sln
- windows/ReactNativeAsyncStorage/ReactNativeAsyncStorage.vcxproj
- windows/code/DBStorage.cpp
- windows/code/DBStorage.h
- windows/code/RNCAsyncStorage.h
- windows/code/ReactPackageProvider.cpp
- windows/code/ReactPackageProvider.h
- windows/code/pch.cpp
- windows/code/pch.h
Lately we saw a number of Watson crash reports in Windows that show crashes due to the result callbacks called twice in case if there are errors related to the database operations. The analysis has shown that the code has no protection from the callbacks being called twice and that the `multiMerge` method is not implemented in a safe way as other methods intended to be.
This PR is relatively big. It is almost a full rewrite of Windows module code. These are the changes:
- To ensure that the result callbacks are called exactly once (not more or less than once) we are adding `Promise` class that invokes the result callback when the `Promise` is resolved or rejected. To ensure that the callback is called not more than once, it uses `m_isCompleted` Boolean atomic variable. To ensure that the …
> fix(windows): Fix crash when running windows module

- package.json
Saw no breaking changes from RN 0.67, so adding support
Fixes https://github.com/react-native-async-storage/async-storage/issues/740
> chore: support RN 0.67

- types/index.d.ts
This change improves the experience for TypeScript users that have the [`unbound-method`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/unbound-method.md) eslint rule enabled. Without this change, check failures occur when users attempt to use destructured references to the functions returned in the `useAsyncStorage` hook's envelope object.
Example:
```typescript
const { getItem, setItem } = useAsyncStorage('someKey')
// eslint@typescript-eslint/unbound-method
//
// Avoid referencing unbound methods which may cause unintentional
// scoping of `this`. If your function does not access `this`, you can
// annotate it with `this: void`, or consider using an arrow function
// instead.
```
This is a type change only, so no direct testing is …
> feat(types): remove `this` binding expectations on hook fn types

- .circleci/config.yml
- package.json
- yarn.lock
This will also address https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
n/a
> chore: bump semantic-release to 19.0

- package.json
- scripts/ios_e2e.sh
- yarn.lock
Bumps react-native-test-app to 1.1.4 to fix issues with Address and Undefined Behavior sanitizers.
> ci: bump react-native-test-app to 1.1.4

- windows/code/DBStorage.cpp
Resolves #755 
In the `MultiRemove` we used a wrong macro `CHECK` instead of `CHECK_SQL_OK` which was failing in successful cases.
Tested manually.
To test manually we run the following commands:
- `yarn install-windows-test-app -p example/windows`
- run `yarn start` in the `example\windows` folder
- open and debug AsyncStorageExample.sln in the `example\windows` folder
> fix(windows): fix MultiRemove by using CHECK_SQL_OK macro

- src/AsyncStorage.native.ts
- src/types.ts
Fix https://github.com/react-native-async-storage/async-storage/issues/764
> Update types.ts to fix wrong void return type of multiGet

- android/build.gradle
- package.json
- website/docs/advanced/Next.md
- yarn.lock
Starting with room 2.4.0-alpha03 arm64 is supported allowing native compile with a arm64 jdk.
1. Get yourself an m1
2. brew tap mdogan/zulu
3. brew install --cask zulu-jdk11
4. java -version (make sure you are running zulu)
5. any repo with rn and async-storage included
6. react-native run android (build will fail)
7. apply patch
8. react-native run android (build will succeed)
> Bump room to 2.4.2, allowing arm64 jdk compile

- android/build.gradle
- android/src/test/java/com/reactnativecommunity/asyncstorage/next/StorageTest.kt
Bumping dependencies for tests, to support jdk17.
Green CI.
> fix(android): Bump test dependencies to support jdk17

- src/types.ts
> fix: `multiRemove` should accept `readonly string[]`

- package.json
- react-native.config.js
- yarn.lock
Consumers are getting "Cannot find module 'react-native-test-app'" when starting Metro dev server.
n/a
> fix: cannot find `react-native-test-app` when Metro starts

- package.json
react-native 0.68 just released. AsyncStorage should be compatible afaik (though I haven't done any super extensive testing).
n/a
> fix: declare support for react-native 0.68

- src/types.ts
Since `getAllKeys` returns `readonly string[]`, it make sense for other functions to accept keys in `readonly`.
Error screenshot:
TS compiles with no errors; tests are passing.
> fix: `multiGet` accepts read-only array

- jest/async-storage-mock.d.ts
- src/index.ts
This is an attempt to address #746. I'm having difficulties reproing this locally. I got a different error when importing the mocks directly which goes away with this.
Resolves #746.
> fix: invalid module name in augmentation

- windows/ReactNativeAsyncStorage/ReactNativeAsyncStorage.vcxproj
Changed to general version for WindowsTargetPlatformVersion
Using an explicit version of WindowsTargetPlatformVersion requires that specific windows SDK version to be installed on the machine.
In Visual Studio 2017 (version 15 or build tools 141) and earlier it was required but as of Visual Studio 2019 (v16 or v142) and Visual Studio 2022(v17 or v143) you can simply specify "10.0". This allows a lot more flexibility to the developer or build machine as there is a growing number of different windows 10 SDK out there now.
You can now install/run on machines without needing as specific of a windows 10.0 version (think of this as saying using the latest version of windows 10 sdk you have installed, so long as it meets the WindowsTargetPlatformMinVersion.
Newer versions of azure hosted windows …
> fix(windows) Change WindowsTargetPlatformVersion to 10.0

- package.json
AsyncStorage should still work fine with react-native 0.69
n/a
> fix: declare support for react-native 0.69

- .circleci/Brewfile.android
- .circleci/config.yml
- package.json
- scripts/android_e2e.sh
Bumping few bits in our CircleCI config. Using Linux machine instead of macos to run Android e2e. Using Test Butler to make sure e2e goes smoothly.
Green CI
> build(ci): Improve Android e2e

- src/AsyncStorage.native.ts
- src/AsyncStorage.ts
- src/hooks.ts
- src/types.ts
- website/docs/API.md
Removes warning about `multiMerge` not being implemented on some platforms. I found implementations for all the platform we care for, so this just looks like some old code that needs cleaning up.
Resolves #818, #826.
> fix: remove warning about `multiMerge` not being implemented

- src/index.ts
Fix [regression](https://github.com/react-native-async-storage/async-storage/commit/db285138137b7d213598961b672be6ed8fade754) by re-introducing the export type statement in the index file.
Relying on automation.
> fix: re-export AsyncStorageStatic type

- .ccache/ccache.conf
- .github/workflows/ci.yml
- package.json
- scripts/macos_e2e.sh
Set up ccache for macOS builds.
CI should pass. First builds should take as much time as it does today, but subsequent ones should be significantly faster.
| Before | After |
| - | - |
| [24m 32s](https://github.com/react-native-async-storage/async-storage/runs/8203935502?check_suite_focus=true) | [13m 31s](https://github.com/react-native-async-storage/async-storage/runs/8204398679?check_suite_focus=true) |
> ci: set up ccache for macOS builds

- yarn.lock
A recent publishing mistake is breaking all Android build regardless of React Native version. This patch release works around the issue. For more details, see https://github.com/facebook/react-native/issues/35210.
> chore: address Android build issues

- website/docs/advanced/Jest-integration.md
> docs: update for Jest 29

- .github/workflows/ci.yml
- .github/workflows/stale.yml
- .github/workflows/website-deployment.yml
We're seeing deprecation warnings on CI such as here: https://github.com/react-native-async-storage/async-storage/actions/runs/3864459872
Bumping all the actions to their latest versions to hopefully get rid of them.
n/a
> ci: bump GitHub actions

- website/docs/help/Troubleshooting.md
Document potential workaround/fix for `inlineRequires` issues. I haven't reproduced this myself, but from the numerous reports (both here and upstream), it sounds like we are hitting cyclic imports.
- https://github.com/react-native-async-storage/async-storage/issues/271
- https://github.com/react-native-async-storage/async-storage/issues/604
- https://github.com/react-native-async-storage/async-storage/issues/634
- https://github.com/react-native-async-storage/async-storage/issues/685
- https://github.com/react-native-async-storage/async-storage/issues/694
- https://github.com/react-native-async-storage/async-storage/issues/814
n/a
> docs: document workaround for `inlineRequires` issues

- website/docs/advanced/Where-data-stored.md
- website/sidebars.js
This is a docs change and relates to issue #905  - adding information on where data is stored.
I placed it under the advanced category in the sidebar. Let me know if you prefer it somewhere else. 
It is a docs change so likely just need to review that the docs run as they should. Let me know if you want me to do any other testing.
Thanks!!
> Add info on where data is stored

- .circleci/config.yml
- .github/workflows/ci.yml
- yarn.lock
Move JS related jobs from CircleCI to GitHub Actions.
> ci: move JS jobs from CircleCI to GH

- .github/Brewfile.ios
- .github/workflows/ci.yml
- scripts/macos_e2e.sh
Copy iOS job from CircleCI. Keep the CircleCI job since we still rely on it for publishing.
> ci: copy iOS job from CircleCI

- .github/workflows/website-deployment.yml
Using Organization secrets to perform website deployments
> website: Update deploy secrets

- .github/workflows/ci.yml
Copy Android unit test job from CircleCI. Keep the CircleCI job since we still rely on it for publishing.
> ci: copy Android unit test job from CircleCI

- .github/workflows/ci.yml
I believe this will fix the deployment.
> fix(deploy): Authenticate Bot as Git author

- package.json
- website/docusaurus.config.js
- website/package.json
- website/yarn.lock
- yarn.lock
Bumped Docusaurus to 2.4.0 and addressed CVEs:
- CVE-2022-3517
- CVE-2022-24999
- CVE-2022-25967
- CVE-2023-23630
```
cd website
yarn
yarn build
yarn serve
```
> docs: bump Docusaurus to 2.4.0

- package.json
- yarn.lock
Addresses https://github.com/react-native-async-storage/async-storage/security/dependabot/112.
For more details, see https://github.com/advisories/GHSA-9c47-m6qq-7p4h
n/a
> chore: address CVE-2022-46175

- website/docs/advanced/Jest-integration.md
`export default from` is not valid JavaScript.
Fixes #946, fixes #895.
Tested manually in a personal project.
> [docs] Fix invalid syntax in Jest integration instructions

- .github/workflows/ci.yml
~Removing release~ Making sure release action is run only on push actions, so that it would not fail, due to lack of access to secrets.
Also, running TS/Lint in a matrix as a bonus
> ci: Separate release action from PR action

- package.json
- yarn.lock
Fix android example app crashing on startup when building release variant.
```
yarn start:android
```
> chore: fix android example app crashing on startup

- react-native.config.js
#910 added TM Support! In that PR we added support for macOS in `react-native.config.js`
Fix a typo in the `sourceDir` config. 
This was tested on macOS but did't cause issues, assuming react-native-test-app takes care of setting up this example dir?
macOS builds
> Fix macOS example block in react-native-config

- .github/workflows/ci.yml
- .github/workflows/website-deployment.yml
- CONTRIBUTING.md
- package.json
- website/docs/advanced/Jest-integration.md
- website/docusaurus.config.js
Ditching `master` in favor of `main`
> chore: move to `main` trunk

- packages/default-storage-backend/RNCAsyncStorage.podspec
Issue: https://github.com/react-native-async-storage/async-storage/issues/997
```shell
npx react-native@0.70.13 init Rn70New --version 0.70.13
cd Rn70New
yarn add "https://gitpkg.now.sh/retyui/async-storage/packages/default-storage-backend?fix-new-arch-pod-install"
RCT_NEW_ARCH_ENABLED=1 npx pod-install
```
> Fix `pod install` on RN 0.70.x + New Arch

- LICENSE
`LICENSE` was moved along with the rest of the code during the monorepo migration. This adds it back to root.
Resolves #1012.
n/a
> chore: add back `LICENSE` file

- packages/default-storage-backend/ios/RNCAsyncStorage.mm
It is not necessary for Apple TV to do a logbox warning about async storage every time the app is reloaded.
This change just places the warning in a `dispatch_once()` so that it occurs only when the app is started.
Tested using the app at https://github.com/douglowder/IgniteTVTest, which has the patch provided in this PR.
> [tvOS] Apple TV warning should only happen once

- packages/default-storage-backend/android/build.gradle
Upcoming react-native 0.73+ includes android gradle plugin 8+ which needs namespace in build.gradle but also needs buildFeatures.buildConfig enabled as well
It is not sufficient to enable this at the top-level app build.gradle, specific modules that use it (such as those that implement new architecture, it seems) must also enable it at the module level
This change was necessary and is in-use in my work app via patch-package as I work through android-gradle-plugin 8+ issues in prep for react-native 0.73 launching for everyone
It is similar to changes I needed to do as react-native-firebase maintainer --> https://github.com/invertase/react-native-firebase/commit/b52d0ce6723c077190618641ce0f33ced9fd4090
With apologies, you have to alter an app that integrates this module to use android …
> fix(android): add buildFeatures.buildConfig for android gradle plugin 8

- packages/default-storage/android/build.gradle
- packages/default-storage/android/config.gradle
- packages/default-storage/example/android/gradle.properties
- packages/default-storage/package.json
- packages/website/docs/advanced/Next.md
- yarn.lock
- Bumped default Kotlin version to 1.9.20
- Coroutines bumped to 1.7.3
- Dropped `kapt` in favor of `ksp`, which version can be set via gradle property
> chore(android): Bump version for Next storage

- package.json
- packages/api/example/ExampleExtension.ts
- packages/api/example/ExampleStorage.ts
- packages/api/package.json
- packages/default-storage/example/examples/Basic.tsx
- packages/default-storage/example/examples/Functional.tsx
- packages/default-storage/example/examples/GetSetClear.tsx
- packages/default-storage/example/examples/MergeItem.tsx
- packages/default-storage/package.json
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/eslint-config/recommended-wdio.js
- yarn.lock
Bump `@rnx-kit/eslint-plugin` to 0.6.0 and simplify ESLint config.
> chore: bump `@rnx-kit/eslint-plugin` to 0.6.0

- packages/website/docs/API.md
This pull request corrects two broken anchor links within the documentation: the links to `#removeItem` and `#multiRemove` subsections in the [clear method](https://react-native-async-storage.github.io/async-storage/docs/api/#clear).
- Updated the anchor link reference from `#removeItem` to `#removeitem` in `API.md`
- Updated the anchor link reference from `#multiRemove` to `#multiremove` in `API.md`
- Tested locally on Brave Version 1.61.114 Chromium: 120.0.6099.199 (Official Build)  (64-bit)
> docs: fix incorrect anchor link casing

- packages/default-storage/RNCAsyncStorage.podspec
Closes #1062 
This PR adds support for [React Native visionOS](https://github.com/callstack/react-native-visionos), the new out-of-tree platform.
You can init a new project with [React Native visionOS](https://github.com/callstack/react-native-visionos), install the library as usual (and apply the one-line change in this PR) and all APIs should be working.
All the APIs used here are already supported in visionOS, so it's just a matter of adding the platform to the podspec for it to get installed.
All the tests still pass. No actual change in C or JS files.
> feat: add visionOS support

- packages/default-storage/README.md
- packages/default-storage/example/examples/Functional.tsx
- packages/default-storage/example/examples/tests.ts
- packages/default-storage/example/ios/AsyncStorageExample/AsyncStorageDevSupport.m
- packages/default-storage/ios/RNCAsyncStorage.mm
- packages/default-storage/scripts/ios_e2e.sh
Passing an empty object to `multiMerge` avoided looping over keys to compare/merge. If the provided object is empty now, simply use the original object instead.
Closes #1046
> fix(ios): Merging empty object should not override current value

- packages/default-storage/ios/RNCAsyncStorage.mm
Before executing the `clear` method on iOS, check if the directory exists using `RCTGetStorageDirectory` to avoid throwing an error.
Fixes #1020 
To test this change I created an app from scratch and call `await AsyncStorage.clear()`.
The component code is available on [gist](https://gist.github.com/camilossantos2809/94af62fd65dce53d1cf77430369cbf92)
before:
https://github.com/react-native-async-storage/async-storage/assets/20076881/0a7e7881-6404-4260-bc58-d23179b29f18
after:
https://github.com/react-native-async-storage/async-storage/assets/20076881/5cafc379-839d-45cf-9c0b-76a2855358e0
> fix: check directory before call delete on iOS

- packages/default-storage/android/build.gradle
- packages/default-storage/android/src/javaPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java
- packages/default-storage/android/src/kotlinPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.kt
This PR tries to fix the `[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null` error when running on react-native@0.74.0-rc.1. The regression was coming from https://github.com/facebook/react-native/pull/41412 and https://github.com/facebook/react-native/issues/43213 has more discussion. This PR follows the [create-react-native-library template to rely on BuildConfig](https://github.com/callstack/react-native-builder-bob/blob/aa4d72367b6dae098cc38f10b04e19daf3499249/packages/create-react-native-library/templates/kotlin-library-mixed/android/src/main/java/com/%7B%25-%20project.package_dir%20%25%7D/%7B%25-%20project.name%20%25%7DPackage.kt#L22)
```sh
$ npx @react-native-community/cli@latest init RN074 --version next
$ cd RN074
$ yarn add @react-native-async-storage/async-storage
$ cd …
```
> fix(android): bridgeless mode broken on react-native 0.74

- packages/default-storage/.gitignore
- packages/default-storage/RNCAsyncStorage.podspec
- packages/default-storage/ios/PrivacyInfo.xcprivacy
- packages/default-storage/ios/RNCAsyncStorage.xcodeproj/project.pbxproj
Async Storage uses timestamp API to perform migration from old storage location. This require us to add a [Privacy Manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc).
Also some leftovers from fabric migration needed to be done
> feat(default-storage): Add Privacy Manifest for iOS

- packages/default-storage/ios/PrivacyInfo.xcprivacy
Apparently, even if the SDK does not collect any data, the Privacy manifest **requires** that entry to be there, even if with an empty array ¯\_(ツ)_/¯
> fix(default-storage): Privacy manifest missing key

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
This creates an extra entry for Expo users when people click on "New Issue"
n/a
> chore: direct Expo users to the forum

- .github/ISSUE_TEMPLATE/config.yml
Our forums are in read-only mode for a while, the Discord servers and channels and forums in there are a recommended way to get in touch with us, and other users.
N/A - forks do not show origin issue templates.
> chore: recommend Expo Discord over read-only forums in issue template

- .changeset/mighty-trains-lick.md
- package.json
That includes [native dependencies bump](https://github.com/react-native-async-storage/async-storage/pull/1094), [type fix for multiSet](https://github.com/react-native-async-storage/async-storage/pull/1103) and some internal dependencies bump
> chore: trigger release for previous chore commits

- .changeset/config.json
- .github/scripts/setup-ci-git-user.sh
- .github/workflows/release.yml
- .github/workflows/website-deployment.yml
- package.json
As per title, setup of git user needs to happen before we publish/release. Also updated setup for website deployment
> fix: Make sure our bot is used for released

- .github/scripts/setup-ci-git-user.sh
- .github/workflows/release.yml
As per title, make sure it's not overridden by the changesets action
> fix: set git credentials locally

- .changeset/config.json
- .github/workflows/release.yml
- .github/workflows/website-deployment.yml
- package.json
- packages/default-storage/CHANGELOG.md
- yarn.lock
Couple of things:
- I still have no idea why GH action is picking gh bot as git credentials (it works fine in a fork), so I'm using variables now for name and email for the bot
- I've noticed during my tests that README would be mixed up by changeset, so I applied changes
- Also I've noticed that one of our releases has not been pushed to npm, so added a warning for it in README
- I've added `api` and `sqlite-storage` to ignore, to avoid changesets releasing it for now (not ready yet)
> chore: yet another follow up for changesets release

- .github/workflows/release.yml
I hope this is the last follow up 😄 Turns out, even if we set git credentials during job run, the `checkout` step had set git credentials upfront, which took precedence over ours. Because of that, github-bot was used to create a branch, not @AsyncStorageBot .
> fix: do not persist credentials for release workflow

- packages/default-storage/metro.config.js
- yarn.lock
Fix Windows example app not loading.
While I was in there, I also removed a dupe of `metro`.
Resolves #1122.
On a Windows machine:
```
cd packages/default-storage
yarn start
```
In a browser, open: `http://localhost:8081/index.bundle?platform=windows&dev=true&hot=true&inlineSourceMap=true`
> chore(windows): fix Windows example app not loading

- .changeset/quiet-snakes-count.md
- packages/default-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
- packages/default-storage/package.json
- yarn.lock
`onCatalystInstanceDestroy` was removed in 0.74, replaced by `invalidate`.
However, `invalidate` was introduced in 0.65: https://github.com/facebook/react-native/commit/18c8417290823e67e211bde241ae9dde27b72f17#diff-736ae7997f3da9751f0f5cf756d8ce4401190bda205c894acc77efe959bd1ecb
And our `package.json` says we still support 0.60: https://github.com/react-native-async-storage/async-storage/blob/fbd4ccf78b9a75d2231935321f7ae0c67811ff0a/packages/default-storage/package.json#L69
In order to make this change, we will also need to bump the minimum version to 0.65. This means we will have to make a major release.
Resolves #1106.
> fix(android): replace `onCatalystInstanceDestroy` with `invalidate`

- packages/website/docs/advanced/Jest-integration.md
Hi! ☀️ 
I noticed that the url to `AsyncStorageMock` files in the [Jest docs](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest#overriding-mock-logic) were leading to a **page not found** error.
I found what I think is the correct url and replaced it. 😄 
Just go to the url and check if it's the correct one to the mocks implementation :)
Thank you! 🙌🏼
> docs: update mock implementation url in Jest integration docs

- packages/website/docs/advanced/Next.md
Kotlin plugin is applied by default on 0.73, so we need to mention versions below 0.73 in the Next documentation
> docs: Mention kotlin plugin setup for RN < 0.73

- packages/website/docs/API.md
Fixes the output example code in the multiMerge API documentation.
This PR fixes the incorrect code output example for multiMerge.
Link Issue: https://github.com/react-native-async-storage/async-storage/issues/1137
Run sample code
> Fixes the output example code multiMerge

- .changeset/modern-bugs-battle.md
- packages/default-storage/ios/RNCAsyncStorage.h
- packages/default-storage/ios/RNCAsyncStorage.mm
At my side of Microsoft, we have recently "vendored" a couple of libraries. Which means, we started building them from source using our own generated Xcode project (not the one cocoapods generates), which has much stricter build flags / treats warnings as errors. In doing so, I caught a couple of issues in React Native async-storage I'd like to push back up!
Namely:
- Fix warnings where we need to add a bunch of either `__nullable` or `__nonnull` specifiers. 
- Fix a "declaration of variable shadows another local variable" where we had two `NSError *error = nil` declarations in a row
- Fix another "declaration of variable shadows another local variable" with two NSError variables by renaming one of them
- Add an `__unused` clang tag to a parameter
- Add `__autoreleaseing` clang tags to …
> chore(apple): fix build issues discovered internally

- .changeset/many-pianos-guess.md
- packages/default-storage/android/src/javaPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java
- packages/default-storage/android/src/kotlinPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.kt
- packages/default-storage/example/android/gradle.properties
The `getViewManagers` overrides aren't doing anything and React Native already provides default implementations. The signature has also been changed in 0.77, breaking builds.
Resolves #1180.
n/a
> fix(android): remove unnecessary `getViewManagers` overrides

- .changeset/curly-carrots-exist.md
- packages/default-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
This interface is now `internal` inside React Native (starting from 0.80) and will be removed in a future version of React Native.
The methods `clearSensitiveData` was never called altogether so it's safe to remove.
I guess I will rely on CI being green here
> [0.80] AsyncStorageModule should not implement ModuleDataCleaner.Cleanable
